service: lambda-internals

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

functions:
  shell:
    handler: handler.shell
  download_code:
    handler: handler.downloadCode

